// <auto-generated />
using System;
using DataIntelligence.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataIntelligence.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DataIntelligenceDbContext))]
    [Migration("20260804110441_InitialTimeSeriesSchema")]
    partial class InitialTimeSeriesSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataIntelligence.Core.Entities.CollectionRun", b =>
                {
                    b.Property<long>("CollectionRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CollectionRunId"));

                    b.Property<DateTime?>("AlertSentAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("Attempt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("DataSourceId")
                        .HasColumnType("tinyint");

                    b.Property<long?>("DurationMs")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasComputedColumnSql("DATEDIFF_BIG(MILLISECOND, [StartedAtUtc], [CompletedAtUtc])");

                    b.Property<string>("ErrorDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FailureCategory")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<short?>("HttpStatusCode")
                        .HasColumnType("smallint");

                    b.Property<int>("ObservationsFetched")
                        .HasColumnType("int");

                    b.Property<int>("ObservationsInserted")
                        .HasColumnType("int");

                    b.Property<int>("ObservationsRejected")
                        .HasColumnType("int");

                    b.Property<int>("ObservationsRevised")
                        .HasColumnType("int");

                    b.Property<int>("ObservationsUnchanged")
                        .HasColumnType("int");

                    b.Property<string>("RequestUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ScheduledForUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("StartedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("CollectionRunId");

                    b.HasIndex("DataSourceId", "ScheduledForUtc", "Attempt")
                        .IsUnique()
                        .HasDatabaseName("UQ_CollectionRun_Cycle");

                    b.HasIndex(new[] { "StartedAtUtc" }, "IX_CollectionRun_Failures")
                        .IsDescending()
                        .HasFilter("[Status] IN ('Failed','PartialSuccess')");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex(new[] { "StartedAtUtc" }, "IX_CollectionRun_Failures"), new[] { "DataSourceId", "FailureCategory", "ErrorMessage", "AlertSentAtUtc" });

                    b.HasIndex(new[] { "StartedAtUtc" }, "IX_CollectionRun_StartedAtUtc")
                        .IsDescending();

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex(new[] { "StartedAtUtc" }, "IX_CollectionRun_StartedAtUtc"), new[] { "DataSourceId", "Status", "ObservationsInserted" });

                    b.ToTable("CollectionRun", "collect", t =>
                        {
                            t.HasCheckConstraint("CK_CollectionRun_Completed", "[CompletedAtUtc] IS NULL OR [CompletedAtUtc] >= [StartedAtUtc]");

                            t.HasCheckConstraint("CK_CollectionRun_Failure", "[FailureCategory] IS NULL OR [FailureCategory] IN ('Unreachable','Timeout','HttpError','RateLimited','ParseError','SchemaChanged','Validation','Persistence','Unknown')");

                            t.HasCheckConstraint("CK_CollectionRun_FailureRequired", "[Status] <> 'Failed' OR [FailureCategory] IS NOT NULL");

                            t.HasCheckConstraint("CK_CollectionRun_Status", "[Status] IN ('Running','Succeeded','PartialSuccess','Failed','Skipped')");

                            t.HasCheckConstraint("CK_CollectionRun_Trigger", "[TriggerType] IN ('Scheduled','Manual','Retry','Backfill')");
                        });
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.DataSource", b =>
                {
                    b.Property<byte>("DataSourceId")
                        .HasColumnType("tinyint");

                    b.Property<string>("AccessMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ApiEndpoint")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<short>("CollectionIntervalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)60);

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasDefaultValue("GET");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LandingPageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("MaxRetries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PublicationCadence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short>("RequestTimeoutSec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)30);

                    b.Property<bool>("RequiresApiKey")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RobotsTxtCheckedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("TermsOfUseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("DataSourceId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_DataSource_Code");

                    b.ToTable("DataSource", "collect", t =>
                        {
                            t.HasCheckConstraint("CK_DataSource_Access", "[AccessMethod] IN ('RestApi','Html','Csv')");

                            t.HasCheckConstraint("CK_DataSource_Cadence", "[PublicationCadence] IN ('BusinessDaily','Daily','Weekly','Monthly','Quarterly','Annual','Irregular')");

                            t.HasCheckConstraint("CK_DataSource_Interval", "[CollectionIntervalMinutes] BETWEEN 1 AND 1440");

                            t.HasCheckConstraint("CK_DataSource_Method", "[HttpMethod] IN ('GET','POST')");

                            t.HasCheckConstraint("CK_DataSource_Timeout", "[RequestTimeoutSec] BETWEEN 1 AND 300");
                        });

                    b.HasData(
                        new
                        {
                            DataSourceId = (byte)1,
                            AccessMethod = "RestApi",
                            ApiEndpoint = "https://api.bls.gov/publicAPI/v2/timeseries/data/",
                            Code = "BLS_CPI",
                            CollectionIntervalMinutes = (short)60,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HttpMethod = "POST",
                            IsEnabled = true,
                            LandingPageUrl = "https://www.bls.gov/data/home.htm",
                            MaxRetries = (byte)3,
                            Name = "US Consumer Price Index",
                            PublicationCadence = "Monthly",
                            Publisher = "U.S. Bureau of Labor Statistics",
                            RequestTimeoutSec = (short)30,
                            RequiresApiKey = false,
                            TermsOfUseUrl = "https://www.bls.gov/developers/api_faqs.htm"
                        },
                        new
                        {
                            DataSourceId = (byte)2,
                            AccessMethod = "RestApi",
                            ApiEndpoint = "https://markets.newyorkfed.org/api/rates/secured/sofr/last/10.json",
                            Code = "NYFED_SOFR",
                            CollectionIntervalMinutes = (short)60,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HttpMethod = "GET",
                            IsEnabled = true,
                            LandingPageUrl = "https://www.newyorkfed.org/markets/reference-rates/sofr",
                            MaxRetries = (byte)3,
                            Name = "Secured Overnight Financing Rate",
                            PublicationCadence = "BusinessDaily",
                            Publisher = "Federal Reserve Bank of New York",
                            RequestTimeoutSec = (short)30,
                            RequiresApiKey = false,
                            TermsOfUseUrl = "https://www.newyorkfed.org/markets/reference-rates/terms-of-use-for-selected-rate-data"
                        });
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.Observation", b =>
                {
                    b.Property<long>("ObservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ObservationId"));

                    b.Property<DateOnly>("ReferenceDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<long>("CollectionRunId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<int>("ReferenceDateKey")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("CONVERT(INT, CONVERT(CHAR(8), [ReferenceDate], 112))", true);

                    b.Property<short>("RevisionNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<byte[]>("RowHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<int>("SeriesId")
                        .HasColumnType("int");

                    b.Property<string>("SourceAnnotation")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SourcePeriodCode")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<DateTime?>("SupersededAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(28,8)");

                    b.HasKey("ObservationId", "ReferenceDate")
                        .HasName("PK_Observation");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("ObservationId", "ReferenceDate"), false);

                    b.HasIndex("CollectionRunId")
                        .HasDatabaseName("IX_Observation_Run");

                    b.HasIndex("ReferenceDate", "SeriesId")
                        .HasDatabaseName("CIX_Observation_Reference");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("ReferenceDate", "SeriesId"));

                    b.HasIndex("SeriesId", "ReferenceDate")
                        .IsUnique()
                        .HasDatabaseName("UQ_Observation_Current")
                        .HasFilter("[IsCurrent] = 1");

                    b.HasIndex("SeriesId", "ReferenceDate", "RevisionNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_Observation_Vintage");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("SeriesId", "ReferenceDate", "RevisionNumber"), false);

                    b.HasIndex(new[] { "SeriesId", "ReferenceDate" }, "IX_Observation_Series_Reference")
                        .IsDescending(false, true);

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex(new[] { "SeriesId", "ReferenceDate" }, "IX_Observation_Series_Reference"), new[] { "Value", "RowHash", "IsCurrent", "PeriodType" });

                    b.ToTable("Observation", "core", t =>
                        {
                            t.HasCheckConstraint("CK_Observation_PeriodType", "[PeriodType] IN ('Day','Week','Month','Quarter','Semiannual','Annual')");

                            t.HasCheckConstraint("CK_Observation_Revision", "[RevisionNumber] >= 0");

                            t.HasCheckConstraint("CK_Observation_Superseded", "([IsCurrent] = 1 AND [SupersededAtUtc] IS NULL) OR ([IsCurrent] = 0 AND [SupersededAtUtc] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.RawPayload", b =>
                {
                    b.Property<long>("RawPayloadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RawPayloadId"));

                    b.Property<long>("CollectionRunId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("CompressedContent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("ContentHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FetchedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("int");

                    b.HasKey("RawPayloadId");

                    b.HasIndex("CollectionRunId")
                        .HasDatabaseName("IX_RawPayload_Run");

                    b.HasIndex("ContentHash", "FetchedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_RawPayload_Hash");

                    b.ToTable("RawPayload", "collect", t =>
                        {
                            t.HasCheckConstraint("CK_RawPayload_Size", "[SizeBytes] >= 0");
                        });
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.RejectedObservation", b =>
                {
                    b.Property<long>("RejectedObservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RejectedObservationId"));

                    b.Property<long>("CollectionRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("RawFragment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ReasonDetail")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReferenceDateText")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RejectedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("SeriesCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RejectedObservationId");

                    b.HasIndex("CollectionRunId", "RejectedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_RejectedObservation_Run");

                    b.ToTable("RejectedObservation", "core", t =>
                        {
                            t.HasCheckConstraint("CK_RejectedObservation_Reason", "[Reason] IN ('MissingField','TypeMismatch','OutOfRange','UnknownSeries','DuplicatePeriod','UnparseablePeriod','SchemaDrift','Unknown')");
                        });
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.Series", b =>
                {
                    b.Property<int>("SeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeriesId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<byte>("DataSourceId")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("DecimalPlaces")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("FirstSeenAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<long?>("FirstSeenRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsSourceAssignedCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SeasonalAdjustment")
                        .IsRequired()
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("SeriesCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourceFieldPath")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("SeriesId");

                    b.HasIndex("FirstSeenRunId");

                    b.HasIndex("CategoryId", "IsActive")
                        .HasDatabaseName("IX_Series_Category");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("CategoryId", "IsActive"), new[] { "Title" });

                    b.HasIndex("DataSourceId", "IsActive")
                        .HasDatabaseName("IX_Series_Source");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("DataSourceId", "IsActive"), new[] { "SeriesCode", "Title" });

                    b.HasIndex("DataSourceId", "SeriesCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Series_Code");

                    b.ToTable("Series", "core", t =>
                        {
                            t.HasCheckConstraint("CK_Series_FieldPath", "[IsSourceAssignedCode] = 1 OR [SourceFieldPath] IS NOT NULL");

                            t.HasCheckConstraint("CK_Series_Frequency", "[Frequency] IN ('BusinessDaily','Daily','Weekly','Monthly','Quarterly','Semiannual','Annual')");

                            t.HasCheckConstraint("CK_Series_Seasonal", "[SeasonalAdjustment] IN ('SeasonallyAdjusted','NotSeasonallyAdjusted','NotApplicable')");

                            t.HasCheckConstraint("CK_Series_SeenOrder", "[LastSeenAtUtc] IS NULL OR [FirstSeenAtUtc] IS NULL OR [LastSeenAtUtc] >= [FirstSeenAtUtc]");
                        });

                    b.HasData(
                        new
                        {
                            SeriesId = 1,
                            CategoryId = 1,
                            DataSourceId = (byte)1,
                            DecimalPlaces = (byte)3,
                            Frequency = "Monthly",
                            IsActive = true,
                            IsSourceAssignedCode = true,
                            SeasonalAdjustment = "NotSeasonallyAdjusted",
                            SeriesCode = "CUUR0000SA0",
                            SourceUrl = "https://www.bls.gov/cpi/",
                            Title = "CPI-U, All items, US city average, not seasonally adjusted",
                            Unit = "Index 1982-84=100"
                        },
                        new
                        {
                            SeriesId = 2,
                            CategoryId = 1,
                            DataSourceId = (byte)1,
                            DecimalPlaces = (byte)3,
                            Frequency = "Monthly",
                            IsActive = true,
                            IsSourceAssignedCode = true,
                            SeasonalAdjustment = "SeasonallyAdjusted",
                            SeriesCode = "CUSR0000SA0",
                            SourceUrl = "https://www.bls.gov/cpi/",
                            Title = "CPI-U, All items, US city average, seasonally adjusted",
                            Unit = "Index 1982-84=100"
                        },
                        new
                        {
                            SeriesId = 3,
                            CategoryId = 2,
                            DataSourceId = (byte)1,
                            DecimalPlaces = (byte)3,
                            Frequency = "Monthly",
                            IsActive = true,
                            IsSourceAssignedCode = true,
                            SeasonalAdjustment = "NotSeasonallyAdjusted",
                            SeriesCode = "CUUR0000SA0L1E",
                            SourceUrl = "https://www.bls.gov/cpi/",
                            Title = "CPI-U, All items less food and energy, not seasonally adjusted",
                            Unit = "Index 1982-84=100"
                        },
                        new
                        {
                            SeriesId = 4,
                            CategoryId = 2,
                            DataSourceId = (byte)1,
                            DecimalPlaces = (byte)3,
                            Frequency = "Monthly",
                            IsActive = true,
                            IsSourceAssignedCode = true,
                            SeasonalAdjustment = "SeasonallyAdjusted",
                            SeriesCode = "CUSR0000SA0L1E",
                            SourceUrl = "https://www.bls.gov/cpi/",
                            Title = "CPI-U, All items less food and energy, seasonally adjusted",
                            Unit = "Index 1982-84=100"
                        },
                        new
                        {
                            SeriesId = 5,
                            CategoryId = 3,
                            DataSourceId = (byte)2,
                            DecimalPlaces = (byte)2,
                            Frequency = "BusinessDaily",
                            IsActive = true,
                            IsSourceAssignedCode = false,
                            SeasonalAdjustment = "NotApplicable",
                            SeriesCode = "SOFR",
                            SourceFieldPath = "percentRate",
                            SourceUrl = "https://www.newyorkfed.org/markets/reference-rates/sofr",
                            Title = "SOFR, overnight rate",
                            Unit = "Percent per annum"
                        },
                        new
                        {
                            SeriesId = 6,
                            CategoryId = 4,
                            DataSourceId = (byte)2,
                            DecimalPlaces = (byte)0,
                            Frequency = "BusinessDaily",
                            IsActive = true,
                            IsSourceAssignedCode = false,
                            SeasonalAdjustment = "NotApplicable",
                            SeriesCode = "SOFR_VOL",
                            SourceFieldPath = "volumeInBillions",
                            SourceUrl = "https://www.newyorkfed.org/markets/reference-rates/sofr",
                            Title = "SOFR, transaction volume",
                            Unit = "USD billions"
                        },
                        new
                        {
                            SeriesId = 7,
                            CategoryId = 4,
                            DataSourceId = (byte)2,
                            DecimalPlaces = (byte)2,
                            Frequency = "BusinessDaily",
                            IsActive = true,
                            IsSourceAssignedCode = false,
                            SeasonalAdjustment = "NotApplicable",
                            SeriesCode = "SOFR_P1",
                            SourceFieldPath = "percentPercentile1",
                            SourceUrl = "https://www.newyorkfed.org/markets/reference-rates/sofr",
                            Title = "SOFR, 1st percentile",
                            Unit = "Percent per annum"
                        },
                        new
                        {
                            SeriesId = 8,
                            CategoryId = 4,
                            DataSourceId = (byte)2,
                            DecimalPlaces = (byte)2,
                            Frequency = "BusinessDaily",
                            IsActive = true,
                            IsSourceAssignedCode = false,
                            SeasonalAdjustment = "NotApplicable",
                            SeriesCode = "SOFR_P25",
                            SourceFieldPath = "percentPercentile25",
                            SourceUrl = "https://www.newyorkfed.org/markets/reference-rates/sofr",
                            Title = "SOFR, 25th percentile",
                            Unit = "Percent per annum"
                        },
                        new
                        {
                            SeriesId = 9,
                            CategoryId = 4,
                            DataSourceId = (byte)2,
                            DecimalPlaces = (byte)2,
                            Frequency = "BusinessDaily",
                            IsActive = true,
                            IsSourceAssignedCode = false,
                            SeasonalAdjustment = "NotApplicable",
                            SeriesCode = "SOFR_P75",
                            SourceFieldPath = "percentPercentile75",
                            SourceUrl = "https://www.newyorkfed.org/markets/reference-rates/sofr",
                            Title = "SOFR, 75th percentile",
                            Unit = "Percent per annum"
                        },
                        new
                        {
                            SeriesId = 10,
                            CategoryId = 4,
                            DataSourceId = (byte)2,
                            DecimalPlaces = (byte)2,
                            Frequency = "BusinessDaily",
                            IsActive = true,
                            IsSourceAssignedCode = false,
                            SeasonalAdjustment = "NotApplicable",
                            SeriesCode = "SOFR_P99",
                            SourceFieldPath = "percentPercentile99",
                            SourceUrl = "https://www.newyorkfed.org/markets/reference-rates/sofr",
                            Title = "SOFR, 99th percentile",
                            Unit = "Percent per annum"
                        });
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.SeriesCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint");

                    b.HasKey("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_SeriesCategory_Code");

                    b.HasIndex(new[] { "ParentCategoryId" }, "IX_SeriesCategory_Parent")
                        .HasFilter("[ParentCategoryId] IS NOT NULL");

                    b.ToTable("SeriesCategory", "core", t =>
                        {
                            t.HasCheckConstraint("CK_SeriesCategory_NotSelfParent", "[ParentCategoryId] <> [CategoryId]");
                        });

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Code = "cpi-headline",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "CPI — All items",
                            SortOrder = (short)10
                        },
                        new
                        {
                            CategoryId = 2,
                            Code = "cpi-core",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "CPI — All items less food and energy",
                            SortOrder = (short)20
                        },
                        new
                        {
                            CategoryId = 3,
                            Code = "sofr-rate",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "SOFR — Rate",
                            SortOrder = (short)30
                        },
                        new
                        {
                            CategoryId = 4,
                            Code = "sofr-liquidity",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "SOFR — Volume and distribution",
                            SortOrder = (short)40
                        });
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.CollectionRun", b =>
                {
                    b.HasOne("DataIntelligence.Core.Entities.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.Observation", b =>
                {
                    b.HasOne("DataIntelligence.Core.Entities.CollectionRun", "Run")
                        .WithMany()
                        .HasForeignKey("CollectionRunId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataIntelligence.Core.Entities.Series", "Series")
                        .WithMany("Observations")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Run");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.RawPayload", b =>
                {
                    b.HasOne("DataIntelligence.Core.Entities.CollectionRun", "Run")
                        .WithMany("RawPayloads")
                        .HasForeignKey("CollectionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.RejectedObservation", b =>
                {
                    b.HasOne("DataIntelligence.Core.Entities.CollectionRun", "Run")
                        .WithMany("RejectedObservations")
                        .HasForeignKey("CollectionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.Series", b =>
                {
                    b.HasOne("DataIntelligence.Core.Entities.SeriesCategory", "Category")
                        .WithMany("Series")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DataIntelligence.Core.Entities.DataSource", "DataSource")
                        .WithMany("Series")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataIntelligence.Core.Entities.CollectionRun", null)
                        .WithMany()
                        .HasForeignKey("FirstSeenRunId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.SeriesCategory", b =>
                {
                    b.HasOne("DataIntelligence.Core.Entities.SeriesCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.CollectionRun", b =>
                {
                    b.Navigation("RawPayloads");

                    b.Navigation("RejectedObservations");
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.DataSource", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.Series", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.SeriesCategory", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
