// <auto-generated />
using System;
using DataIntelligence.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataIntelligence.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DataIntelligenceDbContext))]
    [Migration("20260810113649_AssistantTurnsInTranscriptJson")]
    partial class AssistantTurnsInTranscriptJson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("AssistantTurnId", "ai");

            modelBuilder.Entity("DataIntelligence.Core.Entities.AssistantFeedback", b =>
                {
                    b.Property<long>("AssistantQueryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsHelpful")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("AssistantQueryId");

                    b.ToTable("AssistantFeedback", "ai");
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.AssistantQuery", b =>
                {
                    b.Property<long>("AssistantQueryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AssistantQueryId"));

                    b.Property<string>("AnswerText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AskedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<byte[]>("ClientIpHash")
                        .HasColumnType("binary(32)");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("int");

                    b.Property<string>("ExecutionError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ExecutionMs")
                        .HasColumnType("int");

                    b.Property<string>("ExecutionStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Explanation")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("GeneratedSql")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("ResultRowCount")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SqlParametersJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalLatencyMs")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ValidationDetail")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ValidationOutcome")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("VisualizationJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WasExecuted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("AssistantQueryId");

                    b.HasIndex(new[] { "AskedAtUtc" }, "IX_AssistantQuery_AskedAtUtc")
                        .IsDescending();

                    b.HasIndex(new[] { "AskedAtUtc" }, "IX_AssistantQuery_Rejected")
                        .IsDescending()
                        .HasFilter("[ValidationOutcome] <> 'Approved' AND [ValidationOutcome] <> 'Pending' AND [ValidationOutcome] <> 'NotADataQuestion'");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex(new[] { "AskedAtUtc" }, "IX_AssistantQuery_Rejected"), new[] { "QuestionText", "ValidationOutcome", "ValidationDetail" });

                    b.HasIndex(new[] { "SessionId", "AskedAtUtc" }, "IX_AssistantQuery_Session")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "UserId", "AskedAtUtc" }, "IX_AssistantQuery_User")
                        .IsDescending(false, true);

                    b.ToTable("AssistantQuery", "ai", t =>
                        {
                            t.HasCheckConstraint("CK_AssistantQuery_Execution", "[ExecutionStatus] IS NULL OR [ExecutionStatus] IN ('Succeeded','Failed','Timeout','Cancelled')");

                            t.HasCheckConstraint("CK_AssistantQuery_NoUnvalidatedRun", "[WasExecuted] = 0 OR [ValidationOutcome] = 'Approved'");

                            t.HasCheckConstraint("CK_AssistantQuery_Validation", "[ValidationOutcome] IN ('Pending','Approved','RejectedNotSelect','RejectedForbiddenObject','RejectedSyntax','RejectedComplexity','RejectedNoSql','NotADataQuestion','RejectedUnreadableResponse')");
                        });
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.AssistantSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastActivityAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("StartedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("TranscriptJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SessionId");

                    b.HasIndex("UserId", "StartedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_AssistantSession_User");

                    b.ToTable("AssistantSession", "ai", t =>
                        {
                            t.HasCheckConstraint("CK_AssistantSession_TranscriptJson", "[TranscriptJson] IS NULL OR ISJSON([TranscriptJson]) = 1");
                        });
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.AssistantTurn", b =>
                {
                    b.Property<string>("AnswerText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AskedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<long>("AssistantQueryId")
                        .HasColumnType("bigint");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("int");

                    b.Property<string>("ExecutionError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExecutionMs")
                        .HasColumnType("int");

                    b.Property<string>("ExecutionStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneratedSql")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResultRowCount")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SqlParametersJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalLatencyMs")
                        .HasColumnType("int");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ValidationDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidationOutcome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WasExecuted")
                        .HasColumnType("bit");

                    b.ToTable("AssistantTurns", "ai", t =>
                        {
                            t.ExcludeFromMigrations();
                        });

                    b.ToSqlQuery("SELECT  t.AssistantQueryId,\n        s.SessionId,\n        s.UserId,\n        t.AskedAtUtc,\n        t.QuestionText,\n        t.AnswerText,\n        t.ValidationOutcome,\n        t.ValidationDetail,\n        t.GeneratedSql,\n        t.SqlParametersJson,\n        t.Explanation,\n        t.WasExecuted,\n        t.ExecutionStatus,\n        t.ExecutionError,\n        t.ExecutionMs,\n        t.ResultRowCount,\n        t.ModelName,\n        t.PromptTokens,\n        t.CompletionTokens,\n        t.TotalTokens,\n        t.TotalLatencyMs\nFROM    ai.AssistantSession AS s\nCROSS APPLY OPENJSON(s.TranscriptJson, '$.turns')\nWITH (\n        AssistantQueryId    BIGINT          '$.assistantQueryId',\n        AskedAtUtc          DATETIME2(3)    '$.askedAtPkt',\n        QuestionText        NVARCHAR(2000)  '$.question',\n        AnswerText          NVARCHAR(MAX)   '$.answer',\n        ValidationOutcome   VARCHAR(30)     '$.outcome',\n        ValidationDetail    NVARCHAR(1000)  '$.validationDetail',\n        GeneratedSql        NVARCHAR(MAX)   '$.sql',\n        SqlParametersJson   NVARCHAR(MAX)   '$.parameters' AS JSON,\n        Explanation         NVARCHAR(2000)  '$.explanation',\n        WasExecuted         BIT             '$.wasExecuted',\n        ExecutionStatus     VARCHAR(20)     '$.executionStatus',\n        ExecutionError      NVARCHAR(1000)  '$.executionError',\n        ExecutionMs         INT             '$.executionMs',\n        ResultRowCount      INT             '$.resultRowCount',\n        ModelName           NVARCHAR(100)   '$.modelName',\n        PromptTokens        INT             '$.promptTokens',\n        CompletionTokens    INT             '$.completionTokens',\n        TotalTokens         INT             '$.totalTokens',\n        TotalLatencyMs      INT             '$.totalLatencyMs'\n) AS t");
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.CollectionRun", b =>
                {
                    b.Property<long>("CollectionRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CollectionRunId"));

                    b.Property<DateTime?>("AlertSentAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("Attempt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("DataSourceId")
                        .HasColumnType("tinyint");

                    b.Property<long?>("DurationMs")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasComputedColumnSql("DATEDIFF_BIG(MILLISECOND, [StartedAtUtc], [CompletedAtUtc])");

                    b.Property<string>("ErrorDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FailureCategory")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<short?>("HttpStatusCode")
                        .HasColumnType("smallint");

                    b.Property<int>("ObservationsFetched")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ObservationsInserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ObservationsRejected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ObservationsRevised")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ObservationsUnchanged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("RequestUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ScheduledForUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("StartedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Running");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Scheduled");

                    b.HasKey("CollectionRunId");

                    b.HasIndex("DataSourceId", "ScheduledForUtc", "Attempt")
                        .IsUnique()
                        .HasDatabaseName("UQ_CollectionRun_Cycle");

                    b.HasIndex(new[] { "StartedAtUtc" }, "IX_CollectionRun_Failures")
                        .IsDescending()
                        .HasFilter("[Status] IN ('Failed','PartialSuccess')");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex(new[] { "StartedAtUtc" }, "IX_CollectionRun_Failures"), new[] { "DataSourceId", "FailureCategory", "ErrorMessage", "AlertSentAtUtc" });

                    b.HasIndex(new[] { "StartedAtUtc" }, "IX_CollectionRun_StartedAtUtc")
                        .IsDescending();

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex(new[] { "StartedAtUtc" }, "IX_CollectionRun_StartedAtUtc"), new[] { "DataSourceId", "Status", "ObservationsInserted" });

                    b.ToTable("CollectionRun", "collect", t =>
                        {
                            t.HasCheckConstraint("CK_CollectionRun_Completed", "[CompletedAtUtc] IS NULL OR [CompletedAtUtc] >= [StartedAtUtc]");

                            t.HasCheckConstraint("CK_CollectionRun_Failure", "[FailureCategory] IS NULL OR [FailureCategory] IN ('Unreachable','Timeout','HttpError','RateLimited','ParseError','SchemaChanged','Validation','Persistence','Unknown')");

                            t.HasCheckConstraint("CK_CollectionRun_FailureRequired", "[Status] <> 'Failed' OR [FailureCategory] IS NOT NULL");

                            t.HasCheckConstraint("CK_CollectionRun_Status", "[Status] IN ('Running','Succeeded','PartialSuccess','Failed','Skipped')");

                            t.HasCheckConstraint("CK_CollectionRun_Trigger", "[TriggerType] IN ('Scheduled','Manual','Retry','Backfill')");
                        });
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.CpiObservation", b =>
                {
                    b.Property<long>("CpiObservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CpiObservationId"));

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<long>("CollectionRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("Footnotes")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("IndexValue")
                        .HasColumnType("decimal(12,3)");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PeriodCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateOnly>("ReferenceDate")
                        .HasColumnType("date");

                    b.Property<short>("ReferenceYear")
                        .HasColumnType("smallint");

                    b.Property<short>("RevisionNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<byte[]>("RowHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<string>("SeriesCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("CUUR0000SA0");

                    b.Property<DateTime?>("SupersededAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.HasKey("CpiObservationId")
                        .HasName("PK_CpiObservation");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("CpiObservationId"), false);

                    b.HasIndex("CollectionRunId")
                        .HasDatabaseName("IX_CpiObservation_Run");

                    b.HasIndex("ReferenceYear", "PeriodCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_CpiObservation_Current")
                        .HasFilter("[IsCurrent] = 1");

                    b.HasIndex("ReferenceDate", "PeriodCode", "RevisionNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_Cpi_Vintage");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("ReferenceDate", "PeriodCode", "RevisionNumber"));

                    b.HasIndex(new[] { "PeriodType", "ReferenceDate" }, "IX_CpiObservation_Monthly")
                        .IsDescending(false, true);

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex(new[] { "PeriodType", "ReferenceDate" }, "IX_CpiObservation_Monthly"), new[] { "IndexValue", "RowHash", "IsCurrent", "RevisionNumber" });

                    b.ToTable("CpiObservation", "core", t =>
                        {
                            t.HasCheckConstraint("CK_Cpi_IndexValue", "[IndexValue] > 0");

                            t.HasCheckConstraint("CK_Cpi_PeriodCode", "[PeriodCode] IN ('M01','M02','M03','M04','M05','M06','M07','M08','M09','M10','M11','M12','M13','S01','S02')");

                            t.HasCheckConstraint("CK_Cpi_PeriodType", "([PeriodCode] BETWEEN 'M01' AND 'M12' AND [PeriodType] = 'Month') OR ([PeriodCode] = 'M13' AND [PeriodType] = 'Annual') OR ([PeriodCode] IN ('S01','S02') AND [PeriodType] = 'Semiannual')");

                            t.HasCheckConstraint("CK_Cpi_ReferenceDate", "DAY([ReferenceDate]) = 1 AND YEAR([ReferenceDate]) = [ReferenceYear] AND MONTH([ReferenceDate]) = CASE WHEN [PeriodCode] BETWEEN 'M01' AND 'M12' THEN CONVERT(INT, SUBSTRING([PeriodCode], 2, 2)) WHEN [PeriodCode] = 'S02' THEN 7 ELSE 1 END");

                            t.HasCheckConstraint("CK_Cpi_ReferenceYear", "[ReferenceYear] BETWEEN 1913 AND 2200");

                            t.HasCheckConstraint("CK_Cpi_Revision", "[RevisionNumber] >= 0");

                            t.HasCheckConstraint("CK_Cpi_SeriesCode", "[SeriesCode] = 'CUUR0000SA0'");

                            t.HasCheckConstraint("CK_Cpi_Superseded", "([IsCurrent] = 1 AND [SupersededAtUtc] IS NULL) OR ([IsCurrent] = 0 AND [SupersededAtUtc] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.DataSource", b =>
                {
                    b.Property<byte>("DataSourceId")
                        .HasColumnType("tinyint");

                    b.Property<string>("AccessMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("RestApi");

                    b.Property<string>("ApiEndpoint")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<short>("CollectionIntervalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)60);

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasDefaultValue("GET");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LandingPageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("MaxRetries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PublicationCadence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short>("RequestTimeoutSec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)30);

                    b.Property<bool>("RequiresApiKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("RobotsTxtCheckedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("TermsOfUseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("DataSourceId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_DataSource_Code");

                    b.ToTable("DataSource", "collect", t =>
                        {
                            t.HasCheckConstraint("CK_DataSource_Access", "[AccessMethod] IN ('RestApi','Html','Csv')");

                            t.HasCheckConstraint("CK_DataSource_Cadence", "[PublicationCadence] IN ('BusinessDaily','Daily','Weekly','Monthly','Quarterly','Annual','Irregular')");

                            t.HasCheckConstraint("CK_DataSource_Interval", "[CollectionIntervalMinutes] BETWEEN 1 AND 1440");

                            t.HasCheckConstraint("CK_DataSource_Method", "[HttpMethod] IN ('GET','POST')");

                            t.HasCheckConstraint("CK_DataSource_Timeout", "[RequestTimeoutSec] BETWEEN 1 AND 300");
                        });

                    b.HasData(
                        new
                        {
                            DataSourceId = (byte)1,
                            AccessMethod = "RestApi",
                            ApiEndpoint = "https://api.bls.gov/publicAPI/v2/timeseries/data/",
                            Code = "BLS_CPI",
                            CollectionIntervalMinutes = (short)60,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HttpMethod = "POST",
                            IsEnabled = true,
                            LandingPageUrl = "https://www.bls.gov/data/home.htm",
                            MaxRetries = (byte)3,
                            Name = "US Consumer Price Index (CUUR0000SA0)",
                            PublicationCadence = "Monthly",
                            Publisher = "U.S. Bureau of Labor Statistics",
                            RequestTimeoutSec = (short)30,
                            RequiresApiKey = false,
                            TermsOfUseUrl = "https://www.bls.gov/developers/api_faqs.htm"
                        },
                        new
                        {
                            DataSourceId = (byte)2,
                            AccessMethod = "RestApi",
                            ApiEndpoint = "https://markets.newyorkfed.org/api/rates/secured/sofr/search.json",
                            Code = "NYFED_SOFR",
                            CollectionIntervalMinutes = (short)60,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HttpMethod = "GET",
                            IsEnabled = true,
                            LandingPageUrl = "https://www.newyorkfed.org/markets/reference-rates/sofr",
                            MaxRetries = (byte)3,
                            Name = "Secured Overnight Financing Rate",
                            PublicationCadence = "BusinessDaily",
                            Publisher = "Federal Reserve Bank of New York",
                            RequestTimeoutSec = (short)30,
                            RequiresApiKey = false,
                            TermsOfUseUrl = "https://www.newyorkfed.org/markets/reference-rates/terms-of-use-for-selected-rate-data"
                        });
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.RawPayload", b =>
                {
                    b.Property<long>("RawPayloadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RawPayloadId"));

                    b.Property<long>("CollectionRunId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("CompressedContent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("ContentHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FetchedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("int");

                    b.HasKey("RawPayloadId");

                    b.HasIndex("CollectionRunId")
                        .HasDatabaseName("IX_RawPayload_Run");

                    b.HasIndex("ContentHash", "FetchedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_RawPayload_Hash");

                    b.ToTable("RawPayload", "collect", t =>
                        {
                            t.HasCheckConstraint("CK_RawPayload_Size", "[SizeBytes] >= 0");
                        });
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.RejectedObservation", b =>
                {
                    b.Property<long>("RejectedObservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RejectedObservationId"));

                    b.Property<long>("CollectionRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("RawFragment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ReasonDetail")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReferenceDateText")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RejectedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("SeriesCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RejectedObservationId");

                    b.HasIndex("CollectionRunId", "RejectedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_RejectedObservation_Run");

                    b.ToTable("RejectedObservation", "core", t =>
                        {
                            t.HasCheckConstraint("CK_RejectedObservation_Reason", "[Reason] IN ('MissingField','TypeMismatch','OutOfRange','UnknownSeries','DuplicatePeriod','UnparseablePeriod','SchemaDrift','Unknown')");
                        });
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.SofrDailyRate", b =>
                {
                    b.Property<long>("SofrDailyRateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SofrDailyRateId"));

                    b.Property<decimal?>("Average180DayPercent")
                        .HasColumnType("decimal(9,5)");

                    b.Property<decimal?>("Average30DayPercent")
                        .HasColumnType("decimal(9,5)");

                    b.Property<decimal?>("Average90DayPercent")
                        .HasColumnType("decimal(9,5)");

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<long>("CollectionRunId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("FootnoteId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Percentile1Percent")
                        .HasColumnType("decimal(9,5)");

                    b.Property<decimal?>("Percentile25Percent")
                        .HasColumnType("decimal(9,5)");

                    b.Property<decimal?>("Percentile75Percent")
                        .HasColumnType("decimal(9,5)");

                    b.Property<decimal?>("Percentile99Percent")
                        .HasColumnType("decimal(9,5)");

                    b.Property<decimal>("RatePercent")
                        .HasColumnType("decimal(9,5)");

                    b.Property<string>("RateType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasDefaultValue("SOFR");

                    b.Property<string>("RevisionIndicator")
                        .IsUnicode(false)
                        .HasColumnType("char(1)");

                    b.Property<short>("RevisionNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<byte[]>("RowHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<decimal?>("SofrIndexValue")
                        .HasColumnType("decimal(20,8)");

                    b.Property<DateTime?>("SupersededAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal?>("VolumeUsdBillions")
                        .HasColumnType("decimal(12,3)");

                    b.HasKey("SofrDailyRateId")
                        .HasName("PK_SofrDailyRate");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("SofrDailyRateId"), false);

                    b.HasIndex("CollectionRunId")
                        .HasDatabaseName("IX_SofrDailyRate_Run");

                    b.HasIndex("EffectiveDate")
                        .IsUnique()
                        .HasDatabaseName("UQ_SofrDailyRate_Current")
                        .HasFilter("[IsCurrent] = 1");

                    b.HasIndex("EffectiveDate", "RevisionNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_Sofr_Vintage");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("EffectiveDate", "RevisionNumber"));

                    b.ToTable("SofrDailyRate", "core", t =>
                        {
                            t.HasCheckConstraint("CK_Sofr_PercentileOrder", "([Percentile1Percent] IS NULL OR [Percentile25Percent] IS NULL OR [Percentile1Percent] <= [Percentile25Percent]) AND ([Percentile25Percent] IS NULL OR [Percentile75Percent] IS NULL OR [Percentile25Percent] <= [Percentile75Percent]) AND ([Percentile75Percent] IS NULL OR [Percentile99Percent] IS NULL OR [Percentile75Percent] <= [Percentile99Percent])");

                            t.HasCheckConstraint("CK_Sofr_RateRange", "[RatePercent] BETWEEN -5 AND 25");

                            t.HasCheckConstraint("CK_Sofr_RateType", "[RateType] = 'SOFR'");

                            t.HasCheckConstraint("CK_Sofr_Revision", "[RevisionNumber] >= 0");

                            t.HasCheckConstraint("CK_Sofr_RevisionIndicator", "[RevisionIndicator] IS NULL OR [RevisionIndicator] IN ('Y','N')");

                            t.HasCheckConstraint("CK_Sofr_Superseded", "([IsCurrent] = 1 AND [SupersededAtUtc] IS NULL) OR ([IsCurrent] = 0 AND [SupersededAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Sofr_Volume", "[VolumeUsdBillions] IS NULL OR [VolumeUsdBillions] >= 0");
                        });
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.AssistantQuery", b =>
                {
                    b.HasOne("DataIntelligence.Core.Entities.AssistantSession", "Session")
                        .WithMany("Queries")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.CollectionRun", b =>
                {
                    b.HasOne("DataIntelligence.Core.Entities.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.CpiObservation", b =>
                {
                    b.HasOne("DataIntelligence.Core.Entities.CollectionRun", "Run")
                        .WithMany()
                        .HasForeignKey("CollectionRunId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.RawPayload", b =>
                {
                    b.HasOne("DataIntelligence.Core.Entities.CollectionRun", "Run")
                        .WithMany("RawPayloads")
                        .HasForeignKey("CollectionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.RejectedObservation", b =>
                {
                    b.HasOne("DataIntelligence.Core.Entities.CollectionRun", "Run")
                        .WithMany("RejectedObservations")
                        .HasForeignKey("CollectionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.SofrDailyRate", b =>
                {
                    b.HasOne("DataIntelligence.Core.Entities.CollectionRun", "Run")
                        .WithMany()
                        .HasForeignKey("CollectionRunId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.AssistantSession", b =>
                {
                    b.Navigation("Queries");
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.CollectionRun", b =>
                {
                    b.Navigation("RawPayloads");

                    b.Navigation("RejectedObservations");
                });
#pragma warning restore 612, 618
        }
    }
}
