// <auto-generated />
using System;
using DataIntelligence.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataIntelligence.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DataIntelligenceDbContext))]
    partial class DataIntelligenceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataIntelligence.Core.Entities.AttributeDefinition", b =>
                {
                    b.Property<short>("AttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("AttributeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Unit")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("AttributeId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Attribute_Code");

                    b.ToTable("Attribute", "core", t =>
                        {
                            t.HasCheckConstraint("CK_Attribute_Type", "[DataType] IN ('Text','Number','Date','Boolean')");
                        });
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint");

                    b.HasKey("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Category_Code");

                    b.HasIndex(new[] { "ParentCategoryId" }, "IX_Category_Parent")
                        .HasFilter("[ParentCategoryId] IS NOT NULL");

                    b.ToTable("Category", "core", t =>
                        {
                            t.HasCheckConstraint("CK_Category_NotSelfParent", "[ParentCategoryId] <> [CategoryId]");
                        });
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.CollectionRun", b =>
                {
                    b.Property<long>("CollectionRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CollectionRunId"));

                    b.Property<DateTime?>("AlertSentAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("Attempt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<long?>("DurationMs")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasComputedColumnSql("DATEDIFF_BIG(MILLISECOND, [StartedAtUtc], [CompletedAtUtc])");

                    b.Property<string>("ErrorDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FailureCategory")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<short?>("HttpStatusCode")
                        .HasColumnType("smallint");

                    b.Property<int>("RecordsFetched")
                        .HasColumnType("int");

                    b.Property<int>("RecordsInserted")
                        .HasColumnType("int");

                    b.Property<int>("RecordsRejected")
                        .HasColumnType("int");

                    b.Property<int>("RecordsUnchanged")
                        .HasColumnType("int");

                    b.Property<string>("RequestUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ScheduledForUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("StartedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("CollectionRunId");

                    b.HasIndex("ScheduledForUtc", "Attempt")
                        .IsUnique()
                        .HasDatabaseName("UQ_CollectionRun_Cycle");

                    b.HasIndex(new[] { "StartedAtUtc" }, "IX_CollectionRun_Failures")
                        .IsDescending()
                        .HasFilter("[Status] IN ('Failed','PartialSuccess')");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex(new[] { "StartedAtUtc" }, "IX_CollectionRun_Failures"), new[] { "FailureCategory", "ErrorMessage", "AlertSentAtUtc" });

                    b.HasIndex(new[] { "StartedAtUtc" }, "IX_CollectionRun_StartedAtUtc")
                        .IsDescending();

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex(new[] { "StartedAtUtc" }, "IX_CollectionRun_StartedAtUtc"), new[] { "Status", "RecordsInserted" });

                    b.ToTable("CollectionRun", "collect", t =>
                        {
                            t.HasCheckConstraint("CK_CollectionRun_Completed", "[CompletedAtUtc] IS NULL OR [CompletedAtUtc] >= [StartedAtUtc]");

                            t.HasCheckConstraint("CK_CollectionRun_Failure", "[FailureCategory] IS NULL OR [FailureCategory] IN ('Unreachable','Timeout','HttpError','ParseError','LayoutChanged','Validation','Persistence','Unknown')");

                            t.HasCheckConstraint("CK_CollectionRun_FailureRequired", "[Status] <> 'Failed' OR [FailureCategory] IS NOT NULL");

                            t.HasCheckConstraint("CK_CollectionRun_Status", "[Status] IN ('Running','Succeeded','PartialSuccess','Failed','Skipped')");

                            t.HasCheckConstraint("CK_CollectionRun_Trigger", "[TriggerType] IN ('Scheduled','Manual','Retry','Backfill')");
                        });
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FirstSeenAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<long>("FirstSeenRunId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("ItemId");

                    b.HasIndex("LastSeenAtUtc")
                        .IsDescending()
                        .HasDatabaseName("IX_Item_LastSeen");

                    b.HasIndex("SourceKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_Item_SourceKey");

                    b.HasIndex("CategoryId", "IsActive")
                        .HasDatabaseName("IX_Item_Category");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("CategoryId", "IsActive"), new[] { "Title" });

                    b.ToTable("Item", "core", t =>
                        {
                            t.HasCheckConstraint("CK_Item_SeenOrder", "[LastSeenAtUtc] >= [FirstSeenAtUtc]");
                        });
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.ItemSnapshot", b =>
                {
                    b.Property<long>("ItemSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ItemSnapshotId"));

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("CollectedDateKey")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("CONVERT(INT, CONVERT(CHAR(8), [CollectedAtUtc], 112))", true);

                    b.Property<long>("CollectionRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("char(3)");

                    b.Property<bool>("HasChanged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrimaryValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<decimal?>("SecondaryValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("StatusText")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ItemSnapshotId", "CollectedAtUtc")
                        .HasName("PK_ItemSnapshot");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("ItemSnapshotId", "CollectedAtUtc"), false);

                    b.HasIndex("CollectionRunId")
                        .HasDatabaseName("IX_ItemSnapshot_Run");

                    b.HasIndex("CollectedAtUtc", "ItemId")
                        .HasDatabaseName("CIX_ItemSnapshot_CollectedAtUtc");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("CollectedAtUtc", "ItemId"));

                    b.HasIndex("ItemId", "CollectedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_ItemSnapshot_Item_Time");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ItemId", "CollectedAtUtc"), new[] { "PrimaryValue", "SecondaryValue", "Quantity", "StatusText", "HasChanged", "RowHash" });

                    b.HasIndex("ItemId", "CollectionRunId", "CollectedAtUtc")
                        .IsUnique()
                        .HasDatabaseName("UQ_ItemSnapshot_ItemRun");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("ItemId", "CollectionRunId", "CollectedAtUtc"), false);

                    b.ToTable("ItemSnapshot", "core", t =>
                        {
                            t.HasCheckConstraint("CK_ItemSnapshot_Quantity", "[Quantity] IS NULL OR [Quantity] >= 0");
                        });
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.RawPayload", b =>
                {
                    b.Property<long>("RawPayloadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RawPayloadId"));

                    b.Property<long>("CollectionRunId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("CompressedContent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("ContentHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FetchedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("int");

                    b.HasKey("RawPayloadId");

                    b.HasIndex("CollectionRunId")
                        .HasDatabaseName("IX_RawPayload_Run");

                    b.HasIndex("ContentHash", "FetchedAtUtc")
                        .HasDatabaseName("IX_RawPayload_Hash");

                    b.ToTable("RawPayload", "collect", t =>
                        {
                            t.HasCheckConstraint("CK_RawPayload_Size", "[SizeBytes] >= 0");
                        });
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.RejectedRecord", b =>
                {
                    b.Property<long>("RejectedRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RejectedRecordId"));

                    b.Property<long>("CollectionRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("RawFragment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ReasonDetail")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("RejectedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("RejectedRecordId");

                    b.HasIndex("CollectionRunId", "RejectedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_RejectedRecord_Run");

                    b.ToTable("RejectedRecord", "core", t =>
                        {
                            t.HasCheckConstraint("CK_RejectedRecord_Reason", "[Reason] IN ('MissingField','TypeMismatch','OutOfRange','DuplicateKey','SchemaDrift','Unknown')");
                        });
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.SnapshotAttribute", b =>
                {
                    b.Property<long>("ItemSnapshotId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<short>("AttributeId")
                        .HasColumnType("smallint");

                    b.Property<bool?>("ValueBool")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ValueDate")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal?>("ValueNumber")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ValueText")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("ItemSnapshotId", "CollectedAtUtc", "AttributeId");

                    b.HasIndex("AttributeId")
                        .HasDatabaseName("IX_ItemSnapshotAttribute_Attribute");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("AttributeId"), new[] { "ValueNumber", "ValueText" });

                    b.ToTable("ItemSnapshotAttribute", "core", t =>
                        {
                            t.HasCheckConstraint("CK_ItemSnapshotAttribute_OneValue", "(CASE WHEN [ValueText]   IS NULL THEN 0 ELSE 1 END + CASE WHEN [ValueNumber] IS NULL THEN 0 ELSE 1 END + CASE WHEN [ValueDate]   IS NULL THEN 0 ELSE 1 END + CASE WHEN [ValueBool]   IS NULL THEN 0 ELSE 1 END) = 1");
                        });
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.SourceConfig", b =>
                {
                    b.Property<byte>("SourceConfigId")
                        .HasColumnType("tinyint");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<short>("CollectionIntervalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)60);

                    b.Property<string>("CollectionUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte>("MaxRetries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short>("RequestTimeoutSec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)30);

                    b.Property<DateTime?>("RobotsTxtCheckedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("SourceConfigId");

                    b.ToTable("SourceConfig", "collect", t =>
                        {
                            t.HasCheckConstraint("CK_SourceConfig_Single", "[SourceConfigId] = 1");

                            t.HasCheckConstraint("CK_SourceConfig_Timeout", "[RequestTimeoutSec] BETWEEN 1 AND 300");
                        });
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.Category", b =>
                {
                    b.HasOne("DataIntelligence.Core.Entities.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.Item", b =>
                {
                    b.HasOne("DataIntelligence.Core.Entities.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.ItemSnapshot", b =>
                {
                    b.HasOne("DataIntelligence.Core.Entities.CollectionRun", "Run")
                        .WithMany()
                        .HasForeignKey("CollectionRunId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataIntelligence.Core.Entities.Item", "Item")
                        .WithMany("Snapshots")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.RawPayload", b =>
                {
                    b.HasOne("DataIntelligence.Core.Entities.CollectionRun", "Run")
                        .WithMany("RawPayloads")
                        .HasForeignKey("CollectionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.RejectedRecord", b =>
                {
                    b.HasOne("DataIntelligence.Core.Entities.CollectionRun", "Run")
                        .WithMany("RejectedRecords")
                        .HasForeignKey("CollectionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.SnapshotAttribute", b =>
                {
                    b.HasOne("DataIntelligence.Core.Entities.AttributeDefinition", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataIntelligence.Core.Entities.ItemSnapshot", "Snapshot")
                        .WithMany("Attributes")
                        .HasForeignKey("ItemSnapshotId", "CollectedAtUtc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.CollectionRun", b =>
                {
                    b.Navigation("RawPayloads");

                    b.Navigation("RejectedRecords");
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.Item", b =>
                {
                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("DataIntelligence.Core.Entities.ItemSnapshot", b =>
                {
                    b.Navigation("Attributes");
                });
#pragma warning restore 612, 618
        }
    }
}
